apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: cirros-dv
  name: cirros-dv
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: cirros-dv
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: datavolumedisk1
          interfaces:
          - name: default
            masquerade: {}
          rng: {}
        resources:
          requests:
            memory: 1Gi
      networks:
      - pod: {} # Stock pod network
        name: default
      volumes:
      - dataVolume:
          name: cirros-dv-dv
        name: datavolumedisk1
  dataVolumeTemplates:
  - metadata:
      name: cirros-dv-dv
    spec:
      pvc:
        storageClassName: go-deploy-vms
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
      source:
        registry:
          url: docker://quay.io/kubevirt/cirros-container-disk-demo