apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: ubuntu-dv
  name: ubuntu-dv
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: ubuntu-dv
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: dvdisk1
          - disk:
              bus: virtio
            name: cloudinit
          interfaces:
          - name: default
            masquerade: {}
        resources:
          requests:
            memory: 1Gi
      networks:
      - pod: {} # Stock pod network
        name: default
      volumes:
      - dataVolume:
          name: ubuntu-dv-pvc
        name: dvdisk1
      - cloudInitNoCloud:
          userData: |-
            #cloud-config
            users:
              - default
              - name: cloud
                passwd: $6$rounds=4096$UIgXBH0f$P/GBRWeOe/VKbzjUysjAcGKrRV5w8REGMC7Yo.8aoKYgak0Dl.7P0Bn39Eerwbnz9/AnAFiRa/zHPnOlCv56f0
                shell: /bin/bash
                lock-passwd: false
                ssh_pwauth: True
                chpasswd: { expire: False }
                sudo: ALL=(ALL) NOPASSWD:ALL
                ssh_authorized_keys:
                 - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIF7hmkqCiaD4nL71DriG/NBoekvwxGfO2HFvsH48P0jA emikar@STHRD-43G6KF
            ssh_pwauth: False
        name: cloudinit
  dataVolumeTemplates:
  - metadata:
      name: ubuntu-dv-pvc
    spec:
      pvc:
        storageClassName: go-deploy-vms
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
      source:
        http:
          url: https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img