apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: go-deploy-vms
provisioner: nfs.csi.k8s.io
parameters:
  server: nfs.cloud.cbh.kth.se
  share: /mnt/cloud/apps/sys/deploy/vms
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1